### ISSUE TITLE
jStorage purging items

### ISSUE THREAD

**Issue by fatagun** [andris9/jStorage#101]
Hello,

While trying to persist 2.9 mb and a 1 mb content with jStorage. First request stores them in the localstorage, however the in next request, I dont see the file with 2.9 mb in jStorage wrapper. 

The behavior is not consistent. 

What might be the problem here? What is the capacity of jStorage? why are things being purged?

$.jStorage.storageSize()
2

What is 2 here?
After I jStorage.flush(), 

$.jStorage.storageSize()
32

Can you please elaborate?

**Comment by andris9** [comment]
jStorage stores data as JSON. storageSize returns the string length of that JSON. If you get 2 then it means you have nothing stored and the result is for `"{}"`. If you call flush, then it clears any possible stored data but it also resets internal metadata values to default values that are also stored inside the same JSON string, this is why you get 32 for the second call.

Storing 2.9MB to localStorage probably fails, as browsers support storing up to 5MB but this storage is for raw UTF-16 data which for you would mean about 2.5 MB on "normal" string. jStorage by design swallows all errors silently, in hindsight this is really bad but back in 2009 it seemed like a great idea as no one was actually storing that much data in browser anyway.
